### ISSUE TITLE
Error reported by Wireshark - do I need to import some lua packages maybe?

### ISSUE THREAD

**Issue by MauriceSnell** [roddypratt/router_dissectors#2]
Hi Roddy.  Thanks very much for providing these invaluable tools.

With the latest Wireshark on Win64 (V4.4.0) and your latest SWP-08 dissector, I get this error:
Lua Error: ...ogram Files\Wireshark\plugins\probel_swp08_dissector.lua:209: attempt to index a nil value (global 'bit32')

I wonder if perhaps I need to add Lua packages like bit32 to my Wireshark install somehow?

Thanks for any suggestions,

Maurice Snell

**Comment by roddypratt** [comment]
Good catch - Wireshark 4.4 uses Lua 5.4 which no longer includes the bit32 library. I'll post an update shortly.

Glad to hear you're finding these useful.

**Comment by roddypratt** [comment]
Now resolved,  using the bitop library which is present in all Wireshark versions. 

https://www.wireshark.org/docs/wsdg_html_chunked/_bitwise_operations.html

I've also fixed a bug where SW-P-08 messages crossing a packet boundary weren't reassembled correctly.
